version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/clean_dir
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_node
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_node_app
      timeout: 300
      runas: root
