version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
hooks:
  # BeforeInstall:
  #   - location: scripts/clean_dir
  #     timeout: 300
  #     runas: root
  AfterInstall:
    - location: scripts/install_node.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_node_app.sh
      timeout: 300
      runas: root
