version: 0.2

phases:
  install:
    commands:
      - echo Installing node app and npm
      - sudo apt-get update
      - sudo apt install nodejs -y
      - sudo apt install npm -y
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - mkdir /app
      - cp * /app

artifacts:
  files:
    - /app/*
      
